name: wanderlust
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.0.13
  gradient_borders: ^1.0.1
  flutter_glow: ^0.3.2
  flutter_animator: ^3.2.2
  go_router: ^16.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-VariableFont_wdth,wght.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon4.png
  android: true
  ios: true
  web: false
  android_gravity: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon1.png"
